#!/bin/sh
VERSION="1.0.3_x86_64"

wget "http://files.vagrantup.com/packages/eb590aa3d936ac71cbf9c64cf207f148ddfc000a/vagrant_$VERSION.deb"

sudo dpkg -i "vagrant_$VERSION.deb"

rm "vagrant_$VERSION.deb"
